#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2020-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Bootgly;

#error_reporting(E_ALL); ini_set('display_errors', 'On');

#phpinfo(); exit;

require_once '@/autoload.php';
