<?php

namespace Bootgly\API\Security\Tests\TrustRotationGraceLive;


use function assert;
use function bin2hex;
use function get_class;
use function get_debug_type;
use function getenv;
use function hash;
use function is_array;
use function is_numeric;
use function json_encode;
use function random_bytes;
use function substr;
use RuntimeException;
use Throwable;

use Bootgly\ACI\Tests\Suite\Test;
use Bootgly\ADI\Databases\SQL;
use Bootgly\ADI\Databases\SQL\Operation;
use Bootgly\API\Security\Tokens\Token;
use Bootgly\API\Security\Tokens\Trust;


// ! Opt-in live E2E. An absent opt-in skips; an honoured opt-in must work or
//   fail explicitly so infrastructure trouble cannot resemble a secure result.
$driver = getenv('BOOTGLY_TOK_E2E');
$driver = $driver === false ? '' : $driver;


return new Test(
   description: 'Security/Trust(live): an immediate duplicate of a rotated remember token is benign (requires BOOTGLY_TOK_E2E=mysql|pgsql)',
   skip: $driver === '',
   test: function () use ($driver) {
      if ($driver !== 'mysql' && $driver !== 'pgsql') {
         yield assert(
            assertion: false,
            description: 'TOK-2: BOOTGLY_TOK_E2E must be exactly "mysql" or "pgsql".'
         );

         return;
      }

      $host = getenv('DB_HOST');
      $port = getenv('DB_PORT');
      $database = getenv('DB_NAME');
      $username = getenv('DB_USER');
      $password = getenv('DB_PASSWORD');
      $SSLMode = getenv('DB_SSLMODE');
      $serverKey = getenv('DB_SERVER_PUBLIC_KEY');
      $config = [
         'driver' => $driver,
         'host' => $host === false ? '127.0.0.1' : $host,
         'port' => $port === false ? ($driver === 'mysql' ? 3306 : 5432) : (int) $port,
         'database' => $database === false ? ($driver === 'mysql' ? 'bootgly' : 'postgres') : $database,
         'username' => $username === false ? ($driver === 'mysql' ? 'root' : 'postgres') : $username,
         'password' => $password === false ? '' : $password,
         'timeout' => 8.0,
         'secure' => [
            'mode' => $SSLMode === false ? 'disable' : $SSLMode,
            'key' => $serverKey === false ? '' : $serverKey,
         ],
         'pool' => ['min' => 0, 'max' => 1],
      ];
      $table = 'bootgly_tok2_' . bin2hex(random_bytes(6));
      $tableSQL = $driver === 'mysql' ? "`{$table}`" : "\"{$table}\"";
      $placeholder = $driver === 'mysql' ? '?' : '$1';
      $DDL = $driver === 'mysql'
         ? "CREATE TABLE {$tableSQL} ("
            . 'id BIGINT AUTO_INCREMENT PRIMARY KEY, '
            . 'selector VARCHAR(16) NOT NULL UNIQUE, '
            . 'verifier VARCHAR(64) NOT NULL, '
            . 'previous VARCHAR(64) NULL, '
            . 'rotated BIGINT NULL, '
            . 'user_id VARCHAR(191) NOT NULL, '
            . 'expires BIGINT NOT NULL'
            . ')'
         : "CREATE TABLE {$tableSQL} ("
            . 'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            . 'selector VARCHAR(16) NOT NULL UNIQUE, '
            . 'verifier VARCHAR(64) NOT NULL, '
            . 'previous VARCHAR(64) NULL, '
            . 'rotated BIGINT NULL, '
            . 'user_id TEXT NOT NULL, '
            . 'expires BIGINT NOT NULL'
            . ')';
      $clock = 2_000_000_000;
      $previousTrustGC = Trust::$gcProbability;
      $Database = null;
      $fixtureError = null;
      $cleanupError = null;
      $evidence = [
         'driver' => $driver,
         'issued' => null,
         'winner' => null,
         'duplicate' => null,
         'followup' => null,
         'before' => null,
         'after' => null,
         'final_count' => null,
      ];

      /**
       * Await one live operation and reject recorded driver errors.
       */
      $Await = static function (SQL $Database, string $SQL, array $parameters = []): Operation {
         $Operation = $Database->query($SQL, $parameters);
         $Database->await($Operation);

         if ($Operation->error !== null) {
            throw new RuntimeException($Operation->error);
         }

         return $Operation;
      };
      /**
       * Read the one persisted series without interpreting nullable values.
       *
       * @return null|array<string,mixed>
       */
      $Read = static function (
         SQL $Database,
         string $tableSQL,
         string $placeholder,
         string $selector
      ) use ($Await): null|array {
         $Operation = $Await(
            $Database,
            'SELECT verifier, previous, rotated, user_id, expires '
               . "FROM {$tableSQL} WHERE selector = {$placeholder}",
            [$selector]
         );

         return $Operation->rows[0] ?? null;
      };

      try {
         $Database = new SQL($config);

         try {
            $Await($Database, 'SELECT 1 AS warm');
         }
         catch (Throwable $Failure) {
            throw new RuntimeException(
               "TOK-2: {$driver} live opt-in could not connect with DB_*: {$Failure->getMessage()}",
               previous: $Failure
            );
         }

         $Await($Database, $DDL);
         Trust::$gcProbability = [0, 1];
         $Trust = new Trust($Database, $table);
         $Trust->freeze($clock);

         // # Source to sink: the first request rotates the series. A delayed
         //   sibling then presents the exact pre-rotation token after commit.
         $Issued = $Trust->issue('live-user', 3600);
         $Winner = $Trust->rotate($Issued->value, 3600);
         $evidence['issued'] = get_debug_type($Issued);
         $evidence['winner'] = get_debug_type($Winner);

         if ($Winner instanceof Token) {
            $before = $Read($Database, $tableSQL, $placeholder, $Issued->selector);
            $Duplicate = $Trust->rotate($Issued->value, 3600);
            $after = $Read($Database, $tableSQL, $placeholder, $Issued->selector);
            $Followup = $Trust->rotate($Winner->value, 3600);
            $Count = $Await($Database, "SELECT count(*) AS total FROM {$tableSQL}");

            $evidence['duplicate'] = get_debug_type($Duplicate);
            $evidence['followup'] = get_debug_type($Followup);
            $evidence['before'] = $before;
            $evidence['after'] = $after;
            $evidence['final_count'] = $Count->Result?->cell;
            $evidence['expected_previous'] = hash('sha256', substr($Issued->value, 17));
            $evidence['expected_current'] = hash('sha256', substr($Winner->value, 17));
         }
      }
      catch (Throwable $Failure) {
         $fixtureError = get_class($Failure) . ': ' . $Failure->getMessage();
      }
      finally {
         Trust::$gcProbability = $previousTrustGC;

         if ($Database !== null) {
            try {
               $Cleanup = $Database->query("DROP TABLE IF EXISTS {$tableSQL}");
               $Database->await($Cleanup);

               if ($Cleanup->error !== null) {
                  $cleanupError = $Cleanup->error;
               }
            }
            catch (Throwable $Failure) {
               $cleanupError = get_class($Failure) . ': ' . $Failure->getMessage();
            }
            finally {
               try {
                  $Database->Connection->disconnect();
               }
               catch (Throwable $Failure) {
                  $disconnectError = get_class($Failure) . ': ' . $Failure->getMessage();
                  $cleanupError = $cleanupError === null
                     ? $disconnectError
                     : "{$cleanupError}; {$disconnectError}";
               }
            }
         }
      }

      $before = $evidence['before'];
      $after = $evidence['after'];
      $fixture = $fixtureError === null
         && $cleanupError === null
         && $evidence['issued'] === Token::class
         && $evidence['winner'] === Token::class
         && is_array($before)
         && ($before['verifier'] ?? null) === ($evidence['expected_current'] ?? null);

      yield assert(
         assertion: $fixture,
         description: 'TOK-2: the live fixture must connect, persist the winner and clean its unique table; evidence='
            . json_encode([
               'fixture_error' => $fixtureError,
               'cleanup_error' => $cleanupError,
               'state' => $evidence,
            ])
      );

      $secure = $fixture
         && ($before['previous'] ?? null) === ($evidence['expected_previous'] ?? null)
         && is_numeric($before['rotated'] ?? null)
         && (int) $before['rotated'] === $clock
         && $evidence['duplicate'] === 'null'
         && $evidence['followup'] === Token::class
         && $after === $before
         && is_numeric($evidence['final_count'])
         && (int) $evidence['final_count'] === 1;

      yield assert(
         assertion: $secure,
         description: 'TOK-2 CONFIRMED: a delayed sibling presenting the exact previous validator '
            . 'inside the grace window must decline without authenticating or revoking the live series; evidence='
            . json_encode($evidence)
      );
   }
);
