#!/bin/bash -p
# Bootgly CLI wrapper (auto-generated by: php bootgly setup)
#
# The nearest trusted Bootgly launcher above the working directory runs, so
# this command operates on that workspace. Without one, the launcher recorded
# when setup generated this wrapper is used.
#
# This global convenience wrapper is deliberately unprivileged. PHP bootstraps,
# Composer autoloaders, projects and configuration are executable code beyond
# the entrypoint itself, so the wrapper never promotes any of them to EUID 0.
#
# The tracing JIT is forced on: it cannot be enabled after PHP starts,
# and Bootgly's hot path is measurably slower without it.
# Opt out with BOOTGLY_JIT=0 (required by the native coverage driver).
BINARY=__BOOTGLY_PHP_BINARY__
SCRIPT=__BOOTGLY_FALLBACK_LAUNCHER__
CALLER_UID="$EUID"

if [ "$CALLER_UID" -eq 0 ]; then
   echo 'Refusing to run the Bootgly global wrapper as root.' >&2
   echo 'Use Linux capabilities, a reverse proxy, or invoke an entirely root-controlled deployment explicitly.' >&2
   exit 126
fi

canonical () {
   readlink -f -- "$1" 2>/dev/null
}

trusted () {
   local TARGET="$1"
   local MATCH=''
   local CURRENT=''
   local DIRECT_PARENT=1

   [ -n "$TARGET" ] && [ -f "$TARGET" ] || return 1

   MATCH="$(find "$TARGET" -maxdepth 0 -type f \( -uid "$CALLER_UID" -o -uid 0 \) ! -perm /022 -print -quit 2>/dev/null)"
   [ -n "$MATCH" ] || return 1

   # @ The direct parent may contain executable sibling bootstraps, so it is
   #   never allowed to be writable. Higher root-owned sticky directories
   #   (normally /tmp) are safe because the checked child cannot be replaced.
   CURRENT="${TARGET%/*}"
   [ -n "$CURRENT" ] || CURRENT='/'
   while :; do
      if [ "$DIRECT_PARENT" -eq 1 ]; then
         MATCH="$(find "$CURRENT" -maxdepth 0 -type d \( -uid "$CALLER_UID" -o -uid 0 \) ! -perm /022 -print -quit 2>/dev/null)"
      else
         MATCH="$(find "$CURRENT" -maxdepth 0 -type d \( -uid "$CALLER_UID" -o -uid 0 \) \( ! -perm /022 -o \( -uid 0 -perm -1000 \) \) -print -quit 2>/dev/null)"
      fi
      [ -n "$MATCH" ] || return 1
      [ "$CURRENT" = '/' ] && return 0

      DIRECT_PARENT=0
      CURRENT="${CURRENT%/*}"
      [ -n "$CURRENT" ] || CURRENT='/'
   done
}

BINARY="$(canonical "$BINARY")"
if [ -z "$BINARY" ] || [ ! -x "$BINARY" ] || ! trusted "$BINARY"; then
   echo 'Refusing to execute an untrusted Bootgly PHP binary.' >&2
   exit 126
fi

DIR="$(pwd -P)" || {
   echo 'Refusing to resolve the Bootgly working directory.' >&2
   exit 126
}
while [ -n "$DIR" ]; do
   SOURCE="$DIR/bootgly"
   CANDIDATE="$(canonical "$SOURCE")"
   if [ -n "$CANDIDATE" ] && trusted "$CANDIDATE" && grep -q "define('BOOTGLY_WORKING_BASE'" "$CANDIDATE" 2>/dev/null; then
      SCRIPT="$CANDIDATE"
      break
   fi
   [ "$DIR" = "/" ] && break
   DIR="${DIR%/*}"
   [ -n "$DIR" ] || DIR="/"
done

SCRIPT="$(canonical "$SCRIPT")"
if [ -z "$SCRIPT" ] || ! trusted "$SCRIPT"; then
   echo 'Refusing to execute an untrusted Bootgly launcher.' >&2
   exit 126
fi

if [ "${BOOTGLY_JIT:-1}" = "0" ]; then
   exec "$BINARY" -d opcache.jit=disable "$SCRIPT" "$@"
fi
exec "$BINARY" -d opcache.enable=1 -d opcache.enable_cli=1 -d opcache.jit=tracing -d opcache.jit_buffer_size=256M "$SCRIPT" "$@"
