<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright (c) 2023-present Bootgly and contributors
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Bootgly\commands;


use const BOOTGLY_ROOT_DIR;
use const PHP_BINARY;
use const PHP_EOL;
use function chmod;
use function escapeshellarg;
use function exec;
use function file_exists;
use function file_put_contents;
use function implode;
use function is_dir;
use function is_executable;
use function is_file;
use function is_link;
use function posix_getuid;
use function shell_exec;
use function trim;
use function unlink;

use const Bootgly\CLI;
use Bootgly\CLI\Command;
use Bootgly\CLI\UI\Components\Alert;


class SetupCommand extends Command
{
   // * Config
   public int $group = 0;

   // * Data
   // @ Command
   public string $name = 'setup';
   public string $description = 'Setup Bootgly CLI globally (on /usr/local/bin)';

   /** @var array<string,array<string>> */
   public array $options = [
      // Global options
      'Increase the verbosity of the command' => ['-v', '-vv', '-vvv'],
      'Show help information' => ['--help', '-h'],
      // Local options
      'Uninstall Bootgly CLI from /usr/local/bin' => ['--uninstall'],
      'Grant PHP the ability to bind privileged ports without root' => ['--capabilities'],
   ];


   public function run (array $arguments = [], array $options = []): bool
   {
      // @ Set the name of the script to be installed
      $scriptName = 'bootgly';
      // @ Set the destination directory for global installation
      $installDir = '/usr/local/bin';
      $installPath = "$installDir/$scriptName";

      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      // @ Check if the script is executed with superuser privileges
      if (posix_getuid() !== 0) {
         $Alert->Type::Failure->set();
         $Alert->message = 'This command needs to be executed with superuser privileges.';
         $Alert->render();
         $Output->render('@#yellow:Usage:@; sudo php bootgly setup@.;');
         exit(1);
      }

      // @ Handle --uninstall
      if (isSet($options['uninstall'])) {
         return $this->uninstall($installPath);
      }

      // @ Handle --capabilities
      if (isSet($options['capabilities'])) {
         return $this->capabilities();
      }

      // @ Install
      return $this->install($scriptName, $installDir, $installPath);
   }

   /**
    * Compose the global CLI wrapper script.
    *
    * A wrapper instead of a symlink so that `sudo bootgly` works (sudo resets
    * PATH via secure_path, breaking `#!/usr/bin/env php`).
    *
    * The nearest Bootgly launcher ABOVE the working directory is the one that
    * runs, so the global command operates on the workspace the user stands in
    * — a kit, a platform checkout, the framework itself. The recorded script
    * is only the fallback: it points at the framework of the checkout `setup`
    * ran from, whose launcher boots the AUTHOR context — from a kit, that
    * would list the framework's own projects instead of the user's.
    *
    * JIT is forced at the launcher because it CANNOT be turned on later:
    * `opcache.jit` is not writable at runtime (ini_set() returns false), so a
    * missing php.ini setting is unrecoverable once PHP has started. Bootgly
    * is a long-lived CLI runtime — its hottest functions run fully
    * interpreted without the tracing JIT, which reads as "the framework is
    * slow" rather than "the runtime was misconfigured". BOOTGLY_JIT=0 opts
    * out; the native code-coverage driver needs it.
    *
    * @param string $php Absolute PHP binary path.
    * @param string $script Absolute fallback launcher path.
    *
    * @return string The wrapper script content.
    */
   private function compose (string $php, string $script): string
   {
      // ! Quoted for the shell: this file is written as root into /usr/local/bin
      //   and runs on every invocation — a `$(…)`, a backtick or a quote in the
      //   checkout path would be code there, not a path
      $binary = escapeshellarg($php);
      $launcher = escapeshellarg($script);

      // :
      return <<<WRAPPER
      #!/bin/bash
      # Bootgly CLI wrapper (auto-generated by: sudo php bootgly setup)
      #
      # The nearest Bootgly launcher above the working directory runs, so this
      # command operates on the workspace you stand in; without one, the
      # fallback script (the checkout `setup` ran from) runs.
      #
      # Only a launcher owned by you (or by root) that nobody else can write is
      # trusted: a file merely named `bootgly` in a shared ancestor would
      # otherwise run as you — and as root under `sudo bootgly`.
      #
      # The tracing JIT is forced on: it cannot be enabled after PHP starts,
      # and Bootgly's hot path is measurably slower without it.
      # Opt out with BOOTGLY_JIT=0 (required by the native coverage driver).
      SCRIPT={$launcher}
      OWNER="\${SUDO_USER:-\$(id -un)}"
      trusted () {
         [ -n "\$(find "\$1" -maxdepth 0 \\( -user "\$OWNER" -o -user root \\) ! -perm /022 -print 2>/dev/null)" ]
      }
      DIR="\$PWD"
      while [ -n "\$DIR" ]; do
         if [ -f "\$DIR/bootgly" ] && trusted "\$DIR/bootgly" && grep -q "define('BOOTGLY_WORKING_BASE'" "\$DIR/bootgly" 2>/dev/null; then
            SCRIPT="\$DIR/bootgly"
            break
         fi
         [ "\$DIR" = "/" ] && break
         DIR="\${DIR%/*}"
         [ -n "\$DIR" ] || DIR="/"
      done
      if [ "\${BOOTGLY_JIT:-1}" = "0" ]; then
         exec {$binary} -d opcache.jit=disable "\$SCRIPT" "\$@"
      fi
      exec {$binary} -d opcache.enable=1 -d opcache.enable_cli=1 -d opcache.jit=tracing -d opcache.jit_buffer_size=256M "\$SCRIPT" "\$@"

      WRAPPER;
   }

   private function install (string $scriptName, string $installDir, string $installPath): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      $Output->render('@#green:Installing Bootgly CLI globally...@;@.;');

      // @ Resolve paths
      $phpBinary = PHP_BINARY;
      $scriptPath = BOOTGLY_ROOT_DIR . $scriptName;

      // @ Validate PHP binary
      if ($phpBinary === '' || is_executable($phpBinary) === false) { // @phpstan-ignore-line
         $Alert->Type::Failure->set();
         $Alert->message = 'Could not detect a valid PHP binary.';
         $Alert->render();
         exit(1);
      }

      // @ Validate bootgly script
      if (is_file($scriptPath) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Bootgly script not found at @#cyan:' . $scriptPath . '@;';
         $Alert->render();
         exit(1);
      }

      // @ Check if the destination directory exists
      if (is_dir($installDir) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'The installation directory @#cyan:' . $installDir . '@; does not exist.';
         $Alert->render();
         exit(1);
      }

      // @ Remove old installation (symlink or wrapper) if it exists
      if (file_exists($installPath) || is_link($installPath)) {
         if (unlink($installPath) === false) {
            $Alert->Type::Failure->set();
            $Alert->message = 'Failed to remove existing @#cyan:' . $installPath . '@;';
            $Alert->render();
            exit(1);
         }
      }

      // @ Generate wrapper script with absolute paths
      $wrapper = $this->compose($phpBinary, $scriptPath);

      // @ Write wrapper script
      if (file_put_contents($installPath, $wrapper) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to create wrapper script at @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      // @ Set execution permissions
      if (chmod($installPath, 0755) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to set execution permissions for @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Bootgly CLI installed successfully!';
      $Alert->render();

      $Output->render('  @#yellow:Wrapper:@; @#cyan:' . $installPath . '@;@.;');
      $Output->render('  @#yellow:PHP:    @; @#cyan:' . $phpBinary . '@;@.;');
      $Output->render('  @#yellow:Script: @; @#cyan:' . $scriptPath . '@;@..;');
      $Output->render('You can now use @#green:' . $scriptName . '@; (and @#green:sudo ' . $scriptName . '@;) from any directory.@.;');

      return true;
   }

   private function uninstall (string $installPath): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      if (file_exists($installPath) === false && is_link($installPath) === false) {
         $Output->render('@#yellow:Nothing to uninstall:@; @#cyan:' . $installPath . '@; does not exist.@.;');
         return true;
      }

      if (unlink($installPath) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to remove @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Bootgly CLI uninstalled from @#cyan:' . $installPath . '@;';
      $Alert->render();

      return true;
   }

   private function capabilities (): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      $phpBinary = PHP_BINARY;

      $Output->render('@#green:Granting privileged port binding capability...@;@.;');

      // @ Check if setcap is available
      $setcapPath = trim((string) shell_exec('which setcap 2>/dev/null'));
      if ($setcapPath === '') {
         $Alert->Type::Failure->set();
         $Alert->message = '@#cyan:setcap@; command not found. Install libcap2-bin:';
         $Alert->render();
         $Output->render('  @#yellow:$@; sudo apt install libcap2-bin@.;');
         exit(1);
      }

      // @ Apply CAP_NET_BIND_SERVICE
      $command = escapeshellarg($setcapPath)
         . ' cap_net_bind_service=+ep '
         . escapeshellarg($phpBinary);

      exec($command, $output, $exitCode);
      if ($exitCode !== 0) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to set capabilities on @#cyan:' . $phpBinary . '@;';
         $Alert->render();
         $Output->render(implode(PHP_EOL, $output) . '@.;');
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Capability @#cyan:CAP_NET_BIND_SERVICE@; granted!';
      $Alert->render();

      $Output->render('  @#yellow:Binary:@; @#cyan:' . $phpBinary . '@;@..;');
      $Output->render('PHP can now bind to privileged ports (< 1024) @#green:without sudo@;.@.;');
      $Output->render('@#yellow:Warning:@; this applies to ALL PHP scripts, not just Bootgly.@.;');

      return true;
   }
}
