<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2023-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Bootgly\commands;


use const BOOTGLY_ROOT_DIR;
use const PHP_BINARY;
use const PHP_EOL;
use function chmod;
use function escapeshellarg;
use function exec;
use function file_exists;
use function file_put_contents;
use function implode;
use function is_dir;
use function is_executable;
use function is_file;
use function is_link;
use function posix_getuid;
use function shell_exec;
use function trim;
use function unlink;

use const Bootgly\CLI;
use Bootgly\CLI\Command;
use Bootgly\CLI\UI\Components\Alert;


class SetupCommand extends Command
{
   // * Config
   public int $group = 0;

   // * Data
   // @ Command
   public string $name = 'setup';
   public string $description = 'Setup Bootgly CLI globally (on /usr/local/bin)';

   /** @var array<string,array<string>> */
   public array $options = [
      'Increase the verbosity of the command' => ['-v', '-vv', '-vvv'],
      'Uninstall Bootgly CLI from /usr/local/bin' => ['--uninstall'],
      'Grant PHP the ability to bind privileged ports without root' => ['--capabilities'],
   ];


   public function run (array $arguments = [], array $options = []): bool
   {
      // @ Set the name of the script to be installed
      $scriptName = 'bootgly';
      // @ Set the destination directory for global installation
      $installDir = '/usr/local/bin';
      $installPath = "$installDir/$scriptName";

      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      // @ Check if the script is executed with superuser privileges
      if (posix_getuid() !== 0) {
         $Alert->Type::Failure->set();
         $Alert->message = 'This command needs to be executed with superuser privileges.';
         $Alert->render();
         $Output->render('@#yellow:Usage:@; sudo php bootgly setup@.;');
         exit(1);
      }

      // @ Handle --uninstall
      if (isSet($options['uninstall'])) {
         return $this->uninstall($installPath);
      }

      // @ Handle --capabilities
      if (isSet($options['capabilities'])) {
         return $this->capabilities();
      }

      // @ Install
      return $this->install($scriptName, $installDir, $installPath);
   }

   private function install (string $scriptName, string $installDir, string $installPath): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      $Output->render('@#green:Installing Bootgly CLI globally...@;@.;');

      // @ Resolve paths
      $phpBinary = PHP_BINARY;
      $scriptPath = BOOTGLY_ROOT_DIR . $scriptName;

      // @ Validate PHP binary
      if ($phpBinary === '' || is_executable($phpBinary) === false) { // @phpstan-ignore-line
         $Alert->Type::Failure->set();
         $Alert->message = 'Could not detect a valid PHP binary.';
         $Alert->render();
         exit(1);
      }

      // @ Validate bootgly script
      if (is_file($scriptPath) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Bootgly script not found at @#cyan:' . $scriptPath . '@;';
         $Alert->render();
         exit(1);
      }

      // @ Check if the destination directory exists
      if (is_dir($installDir) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'The installation directory @#cyan:' . $installDir . '@; does not exist.';
         $Alert->render();
         exit(1);
      }

      // @ Remove old installation (symlink or wrapper) if it exists
      if (file_exists($installPath) || is_link($installPath)) {
         if (unlink($installPath) === false) {
            $Alert->Type::Failure->set();
            $Alert->message = 'Failed to remove existing @#cyan:' . $installPath . '@;';
            $Alert->render();
            exit(1);
         }
      }

      // @ Generate wrapper script with absolute paths
      // Using a wrapper instead of a symlink so that `sudo bootgly` works
      // (sudo resets PATH via secure_path, breaking `#!/usr/bin/env php`)
      $wrapper = "#!/bin/bash\n"
         . "# Bootgly CLI wrapper (auto-generated by: sudo php bootgly setup)\n"
         . "# PHP: $phpBinary\n"
         . "# Script: $scriptPath\n"
         . "exec \"$phpBinary\" \"$scriptPath\" \"\$@\"\n";

      // @ Write wrapper script
      if (file_put_contents($installPath, $wrapper) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to create wrapper script at @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      // @ Set execution permissions
      if (chmod($installPath, 0755) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to set execution permissions for @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Bootgly CLI installed successfully!';
      $Alert->render();

      $Output->render('  @#yellow:Wrapper:@; @#cyan:' . $installPath . '@;@.;');
      $Output->render('  @#yellow:PHP:    @; @#cyan:' . $phpBinary . '@;@.;');
      $Output->render('  @#yellow:Script: @; @#cyan:' . $scriptPath . '@;@..;');
      $Output->render('You can now use @#green:' . $scriptName . '@; (and @#green:sudo ' . $scriptName . '@;) from any directory.@.;');

      return true;
   }

   private function uninstall (string $installPath): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      if (file_exists($installPath) === false && is_link($installPath) === false) {
         $Output->render('@#yellow:Nothing to uninstall:@; @#cyan:' . $installPath . '@; does not exist.@.;');
         return true;
      }

      if (unlink($installPath) === false) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to remove @#cyan:' . $installPath . '@;';
         $Alert->render();
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Bootgly CLI uninstalled from @#cyan:' . $installPath . '@;';
      $Alert->render();

      return true;
   }

   private function capabilities (): bool
   {
      $Output = CLI->Terminal->Output;
      $Alert = new Alert($Output);

      $phpBinary = PHP_BINARY;

      $Output->render('@#green:Granting privileged port binding capability...@;@.;');

      // @ Check if setcap is available
      $setcapPath = trim((string) shell_exec('which setcap 2>/dev/null'));
      if ($setcapPath === '') {
         $Alert->Type::Failure->set();
         $Alert->message = '@#cyan:setcap@; command not found. Install libcap2-bin:';
         $Alert->render();
         $Output->render('  @#yellow:$@; sudo apt install libcap2-bin@.;');
         exit(1);
      }

      // @ Apply CAP_NET_BIND_SERVICE
      $command = escapeshellarg($setcapPath)
         . ' cap_net_bind_service=+ep '
         . escapeshellarg($phpBinary);

      exec($command, $output, $exitCode);
      if ($exitCode !== 0) {
         $Alert->Type::Failure->set();
         $Alert->message = 'Failed to set capabilities on @#cyan:' . $phpBinary . '@;';
         $Alert->render();
         $Output->render(implode(PHP_EOL, $output) . '@.;');
         exit(1);
      }

      $Alert->Type::Success->set();
      $Alert->message = 'Capability @#cyan:CAP_NET_BIND_SERVICE@; granted!';
      $Alert->render();

      $Output->render('  @#yellow:Binary:@; @#cyan:' . $phpBinary . '@;@..;');
      $Output->render('PHP can now bind to privileged ports (< 1024) @#green:without sudo@;.@.;');
      $Output->render('@#yellow:Warning:@; this applies to ALL PHP scripts, not just Bootgly.@.;');

      return true;
   }
}
