<?php

namespace Bootgly\ADI\Databases\SQL\Repository\Tests\Async;


use function assert;
use function getenv;
use function stream_select;
use RuntimeException;

use Bootgly\ACI\Events\Scheduler;
use Bootgly\ACI\Tests\Suite\Test\Specification;
use Bootgly\ADI\Databases\SQL;
use Bootgly\ADI\Databases\SQL\Model\Column;
use Bootgly\ADI\Databases\SQL\Model\Key;
use Bootgly\ADI\Databases\SQL\Model\Table;
use Bootgly\ADI\Databases\SQL\Operation;


#[Table('orm_async_users')]
class AsyncUser
{
   #[Key]
   public null|int $id = null;
   #[Column]
   public string $name = '';
}


return new Specification(
   description: 'Database: SQL ORM executes through the native async PostgreSQL driver',
   skip: getenv('BOOTGLY_ORM_ASYNC_E2E') !== '1',
   test: function () {
      /**
       * @return array{Operation,bool}
       */
      $await = static function (SQL $Database, Operation $Operation): array {
         $readied = false;
         $attempts = 0;

         while ($Operation->finished === false && $attempts < 200) {
            $Database->advance($Operation);

            if ($Operation->Readiness !== null) {
               $readied = true;
               $Readiness = $Operation->Readiness;
               $reads = $Readiness->flag === Scheduler::SCHEDULE_READ ? [$Readiness->socket] : [];
               $writes = $Readiness->flag === Scheduler::SCHEDULE_WRITE ? [$Readiness->socket] : [];
               $except = [];

               if ($reads !== [] || $writes !== []) {
                  stream_select($reads, $writes, $except, 1, 0);
               }
            }

            $attempts++;
         }

         if ($Operation->finished === false) {
            throw new RuntimeException('ORM async operation did not finish.');
         }

         if ($Operation->error !== null) {
            throw new RuntimeException($Operation->error);
         }

         return [$Operation, $readied];
      };

      $Database = new SQL([
         'driver' => 'pgsql',
         'host' => getenv('DB_HOST') ?: '127.0.0.1',
         'port' => getenv('DB_PORT') ?: 5432,
         'database' => getenv('DB_NAME') ?: 'bootgly',
         'username' => getenv('DB_USER') ?: 'postgres',
         'password' => getenv('DB_PASS') ?: '',
         'secure' => ['mode' => 'disable'],
         'pool' => ['min' => 0, 'max' => 1],
         'timeout' => 5.0,
      ]);
      $readiness = false;

      [$Operation, $ready] = $await($Database, $Database->query('DROP TABLE IF EXISTS orm_async_users'));
      $readiness = $readiness || $ready;
      [$Operation, $ready] = $await($Database, $Database->query('CREATE TABLE orm_async_users (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL)'));
      $readiness = $readiness || $ready;

      $Repository = $Database->map(AsyncUser::class);
      $User = new AsyncUser;
      $User->name = 'Async Ada';
      [$Operation, $ready] = $await($Database, $Repository->save($User));
      $readiness = $readiness || $ready;
      $Mapped = $Repository->hydrate($Operation);
      /** @var AsyncUser $Saved */
      $Saved = $Mapped->entity;

      yield assert(
         assertion: $Saved instanceof AsyncUser
            && $Saved->id !== null
            && $Saved->name === 'Async Ada',
         description: 'Repository::save executes through a real async PostgreSQL operation and hydrates RETURNING rows'
      );

      [$Operation, $ready] = $await($Database, $Repository->find($Saved->id));
      $readiness = $readiness || $ready;
      $Mapped = $Repository->hydrate($Operation);

      yield assert(
         assertion: $Mapped->entity === $Saved
            && $readiness,
         description: 'Repository::find advances through Operation Readiness and reuses the ORM identity map'
      );

      $await($Database, $Database->query('DROP TABLE IF EXISTS orm_async_users'));
   }
);
