<?php

namespace Bootgly\ADI\Databases\SQL\Schema\Tests\DDL;


use function assert;
use function preg_match;
use function strlen;
use InvalidArgumentException;

use Bootgly\ACI\Tests\Suite\Test\Specification;
use Bootgly\ADI\Databases\SQL;
use Bootgly\ADI\Databases\SQL\Builder\Expression;
use Bootgly\ADI\Databases\SQL\Schema as SQLSchema;
use Bootgly\ADI\Databases\SQL\Schema\Auxiliaries\Capabilities;
use Bootgly\ADI\Databases\SQL\Schema\Auxiliaries\Keys;
use Bootgly\ADI\Databases\SQL\Schema\Auxiliaries\References;
use Bootgly\ADI\Databases\SQL\Schema\Auxiliaries\Types;
use Bootgly\ADI\Databases\SQL\Schema\Blueprint;


enum Tables: string
{
   case Teams = 'teams';
   case Users = 'users';
}

enum Columns: string
{
   case Active = 'active';
   case Created = 'created_at';
   case Email = 'email';
   case Id = 'id';
   case Legacy = 'legacy';
   case Team = 'team_id';
}


return new Specification(
   description: 'Database: SQL schema builder compiles PostgreSQL DDL',
   test: function () {
      $Database = new SQL;
      $Schema = $Database->structure();

      yield assert(
         assertion: $Schema === $Database->structure(),
         description: 'SQL facade caches the Schema structure builder'
      );

      $Direct = new SQLSchema($Schema->Dialect);

      yield assert(
         assertion: $Direct->Dialect === $Schema->Dialect,
         description: 'Schema accepts resolved dialect instances directly'
      );

      yield assert(
         assertion: $Schema->Dialect->check(Capabilities::AlterColumnUsing)
            && $Schema->Dialect->check(Capabilities::DropConstraint)
            && $Schema->Dialect->check(Capabilities::MultiActionAlter),
         description: 'Schema reports PostgreSQL dialect capabilities'
      );

      $Query = $Schema->create(Tables::Users, function (Blueprint $Table): void {
         $Table->add(Columns::Id, Types::BigInteger)
            ->generate()
            ->constrain(Keys::Primary);
         $Table->add(Columns::Email, Types::String)
            ->limit(190)
            ->constrain(Keys::Unique);
         $Table->add(Columns::Active, Types::Boolean)
            ->default(true);
         $Table->add(Columns::Created, Types::Timestamp)
            ->default(new Expression('CURRENT_TIMESTAMP'));
      });

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "email" VARCHAR(190) NOT NULL UNIQUE, "active" BOOLEAN NOT NULL DEFAULT TRUE, "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)',
         description: 'Schema compiles CREATE TABLE with practical column modifiers'
      );

      $Query = $Schema->create('settings', function (Blueprint $Table): void {
         $Table->add('key');
      }, exists: true);

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE IF NOT EXISTS "settings" ("key" TEXT NOT NULL)',
         description: 'Schema compiles idempotent CREATE TABLE with Text as default type'
      );

      $Query = $Schema->create('memberships', function (Blueprint $Table): void {
         $Table->add(Columns::Team, Types::BigInteger)
            ->reference(Tables::Teams, Columns::Id);
      });

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE "memberships" ("team_id" BIGINT NOT NULL REFERENCES "teams" ("id"))',
         description: 'Schema compiles inline enum foreign key references'
      );

      $Query = $Schema->create('events', function (Blueprint $Table): void {
         $Table->add('payload', Types::Json);
         $Table->add('snapshot', Types::JsonB);
      });

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE "events" ("payload" JSON NOT NULL, "snapshot" JSONB NOT NULL)',
         description: 'Schema distinguishes PostgreSQL JSON and JSONB types'
      );

      $Query = $Schema->alter(Tables::Users, function (Blueprint $Table): void {
         $Table->add('bio', Types::Text)->allow();
         $Table->remove(Columns::Legacy);
         $Table->reference(Columns::Team, Tables::Teams, Columns::Id)
            ->delete(References::Cascade)
            ->update(References::Restrict);
      });

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "users" ADD COLUMN "bio" TEXT, DROP COLUMN "legacy", ADD CONSTRAINT "users_team_id_teams_fk" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE ON UPDATE RESTRICT',
         description: 'Schema compiles ALTER TABLE add/drop/foreign-key actions'
      );

      $Query = $Schema->alter('memberships', function (Blueprint $Table): void {
         $Table->reference('subject_id', 'users');
         $Table->reference('subject_id', 'teams');
      });

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "memberships" ADD CONSTRAINT "memberships_subject_id_users_fk" FOREIGN KEY ("subject_id") REFERENCES "users" ("id"), ADD CONSTRAINT "memberships_subject_id_teams_fk" FOREIGN KEY ("subject_id") REFERENCES "teams" ("id")',
         description: 'Schema includes target tables in generated foreign key names'
      );

      $Query = $Schema->alter('very_long_memberships_table_name_for_foreign_key_identifier_limits', function (Blueprint $Table): void {
         $Table->reference('very_long_subject_identifier_column_name', 'very_long_target_table_identifier_name');
      });
      preg_match('/ADD CONSTRAINT "([^"]+)"/', $Query->sql, $matches);

      yield assert(
         assertion: isset($matches[1]) && strlen($matches[1]) <= 63,
         description: 'Schema truncates long generated foreign key names'
      );

      $Query = $Schema->alter(Tables::Users, function (Blueprint $Table): void {
         $Table->change(Columns::Email, Types::String)->limit(320);
         $Table->change('legacy_id', Types::BigInteger)->cast(new Expression('legacy_id::bigint'));
         $Table->rename('bio', 'profile');
         $Table->allow(Columns::Active);
         $Table->require(Columns::Email);
         $Table->default(Columns::Active, false);
         $Table->undefault(Columns::Created);
      });

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "users" ALTER COLUMN "email" TYPE VARCHAR(320), ALTER COLUMN "legacy_id" TYPE BIGINT USING legacy_id::bigint, RENAME COLUMN "bio" TO "profile", ALTER COLUMN "active" DROP NOT NULL, ALTER COLUMN "email" SET NOT NULL, ALTER COLUMN "active" SET DEFAULT FALSE, ALTER COLUMN "created_at" DROP DEFAULT',
         description: 'Schema compiles ALTER COLUMN type rename nullability and default actions'
      );

      $Query = $Schema->index(Tables::Users, [Columns::Email, Columns::Created], unique: true);

      yield assert(
         assertion: $Query->sql === 'CREATE UNIQUE INDEX "users_email_created_at_unique" ON "users" ("email", "created_at")',
         description: 'Schema compiles conventional unique indexes'
      );

      $Query = $Schema->index(
         'very_long_reporting_events_table_name_for_postgresql_identifier_limits',
         ['extremely_long_first_column_name', 'extremely_long_second_column_name']
      );
      preg_match('/^CREATE INDEX "([^"]+)"/', $Query->sql, $matches);

      yield assert(
         assertion: isset($matches[1]) && strlen($matches[1]) <= 63,
         description: 'Schema truncates long conventional index names'
      );

      $Query = $Schema->unindex(Tables::Users, 'users_email_created_at_unique');

      yield assert(
         assertion: $Query->sql === 'DROP INDEX IF EXISTS "users_email_created_at_unique"',
         description: 'Schema compiles safe DROP INDEX by default'
      );

      yield assert(
         assertion: $Schema->unindex('audit.users', 'users_email_index')->sql === 'DROP INDEX IF EXISTS "audit"."users_email_index"',
         description: 'Schema uses PostgreSQL table schema to qualify dropped indexes'
      );

      $Query = $Schema->unconstrain(Tables::Users, 'users_team_id_teams_fk');

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_team_id_teams_fk"',
         description: 'Schema compiles safe DROP CONSTRAINT by default'
      );

      $Query = $Schema->rename(Tables::Users, 'members');

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "users" RENAME TO "members"',
         description: 'Schema compiles RENAME TABLE statements'
      );

      $Query = $Schema->drop(Tables::Users);

      yield assert(
         assertion: $Query->sql === 'DROP TABLE IF EXISTS "users"',
         description: 'Schema compiles safe DROP TABLE by default'
      );

      $blocked = false;

      try {
         $Schema->create('empty', function (Blueprint $Table): void {
            // Empty blueprint intentionally rejected.
         });
      }
      catch (InvalidArgumentException) {
         $blocked = true;
      }

      yield assert(
         assertion: $blocked,
         description: 'Schema rejects empty CREATE TABLE blueprints'
      );

      $MySQL = (new SQL(['driver' => 'mysql']))->structure();

      yield assert(
         assertion: $MySQL->Dialect->check(Capabilities::AlterColumnType)
            && $MySQL->Dialect->check(Capabilities::AlterColumnDefault)
            && $MySQL->Dialect->check(Capabilities::DropConstraint)
            && $MySQL->Dialect->check(Capabilities::AlterColumnUsing) === false
            && $MySQL->Dialect->check(Capabilities::AlterColumnNullability) === false,
         description: 'Schema reports MySQL dialect capabilities'
      );

      $Query = $MySQL->create(Tables::Users, function (Blueprint $Table): void {
         $Table->add(Columns::Id, Types::BigInteger)
            ->generate()
            ->constrain(Keys::Primary);
         $Table->add(Columns::Email, Types::String)
            ->limit(190)
            ->constrain(Keys::Unique);
         $Table->reference(Columns::Team, Tables::Teams)
            ->delete(References::Cascade);
      }, exists: true);

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE IF NOT EXISTS `users` (`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, `email` VARCHAR(190) NOT NULL UNIQUE, CONSTRAINT `users_team_id_teams_fk` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE CASCADE)',
         description: 'Schema compiles MySQL CREATE TABLE with foreign keys'
      );

      yield assert(
         assertion: $MySQL->unindex(Tables::Users, 'users_email_index')->sql === 'DROP INDEX `users_email_index` ON `users`'
            && $MySQL->rename(Tables::Users, 'members')->sql === 'RENAME TABLE `users` TO `members`',
         description: 'Schema compiles MySQL DROP INDEX and RENAME TABLE'
      );

      $SQLite = (new SQL(['driver' => 'sqlite']))->structure();

      yield assert(
         assertion: $SQLite->Dialect->check(Capabilities::RenameColumn)
            && $SQLite->Dialect->check(Capabilities::DropColumn)
            && $SQLite->Dialect->check(Capabilities::AlterColumnType) === false
            && $SQLite->Dialect->check(Capabilities::AlterColumnDefault) === false
            && $SQLite->Dialect->check(Capabilities::DropConstraint) === false
            && $SQLite->Dialect->check(Capabilities::MultiActionAlter) === false,
         description: 'Schema reports SQLite dialect capabilities'
      );

      $Query = $SQLite->create(Tables::Users, function (Blueprint $Table): void {
         $Table->add(Columns::Id, Types::BigInteger)
            ->generate()
            ->constrain(Keys::Primary);
         $Table->add(Columns::Email, Types::String)
            ->limit(190)
            ->constrain(Keys::Unique);
      }, exists: true);

      yield assert(
         assertion: $Query->sql === 'CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" TEXT NOT NULL UNIQUE)',
         description: 'Schema compiles SQLite CREATE TABLE with autoincrement primary key'
      );

      $Query = $SQLite->alter(Tables::Users, function (Blueprint $Table): void {
         $Table->rename(Columns::Email, 'contact');
      });

      yield assert(
         assertion: $Query->sql === 'ALTER TABLE "users" RENAME COLUMN "email" TO "contact"'
            && $SQLite->unindex(Tables::Users, 'users_email_index')->sql === 'DROP INDEX IF EXISTS "users_email_index"',
         description: 'Schema compiles SQLite ALTER RENAME COLUMN and DROP INDEX'
      );
   }
);
