#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2020-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace scripts;


require __DIR__ . '/../autoload.php';


use Bootgly\Web\nodes\HTTP;


$HTTPServer = new HTTP\Server;
$HTTPServer->configure(
   host: '0.0.0.0',
   port: getenv('PORT') ? getenv('PORT') : 8080,
   workers: round( ((int) shell_exec('nproc')) * 0.55 ), // Without JIT: * 0.6
   /*
   ssl: [
      // SSL Certificate
      'local_cert'  => __DIR__ . '/@/certificates/localhost.cert.pem',
      // SSL Keyfile
      'local_pk'    => __DIR__ . '/@/certificates/localhost.key.pem',

      'disable_compression' => true, // TLS compression attack vulnerability

      'ssltransport' => 'tlsv1.3',

      'ciphers' => 'AES256-SHA256',

      'verify_peer' => false,
      #'verify_peer_name' => true,
      #'capture_peer_cert' => true,
   ]
   */
);
// on Data -> projects/Bootgly/Web/HTTP-Server.API.php
$HTTPServer->start();
