#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2023-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace scripts;


@include __DIR__ . '/../autoload.php';


use Bootgly\WPI\Nodes\HTTP_Server_CLI;


$HTTP_Server_CLI = new HTTP_Server_CLI;
$HTTP_Server_CLI->configure(
   host: '0.0.0.0',
   port: getenv('PORT') ? getenv('PORT'): 8082,
   workers: round(((int) shell_exec('nproc')) * 0.6),
   /*
   ssl: [
      // SSL Certificate
      'local_cert'  => __DIR__ . '/@/certificates/localhost.cert.pem',
      // SSL Keyfile
      'local_pk'    => __DIR__ . '/@/certificates/localhost.key.pem',

      'disable_compression' => true, // TLS compression attack vulnerability

      'ssltransport' => 'tlsv1.3',

      'ciphers' => 'AES256-SHA256',

      'verify_peer' => false,
      #'verify_peer_name' => true,
      #'capture_peer_cert' => true,
   ]
   */
);
// on Data -> projects/Bootgly/WPI/HTTP_Server_CLI-1.SAPI.php
$HTTP_Server_CLI->start();
