#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2023-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Bootgly;


require __DIR__ . '/../autoload.php';


use Bootgly\WPI\Interfaces\TCP;


$TCP_Server = new TCP\Server;
$TCP_Server->configure(
   host: '0.0.0.0',
   port: getenv('PORT') ? getenv('PORT') : 8080,
   workers: 12
);
// on Data -> projects/Bootgly/WPI/TCP_Server_CLI.SAPI.php
$TCP_Server->start();
