#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2023-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

namespace Bootgly;


@include __DIR__ . '/../autoload.php';


use Bootgly\WPI\Interfaces\TCP_Server_CLI;


$TCP_Server_CLI = new TCP_Server_CLI;
$TCP_Server_CLI->configure(
   host: '0.0.0.0',
   port: getenv('PORT') ? getenv('PORT'): 8080,
   workers: 12
);
// on Data -> projects/Bootgly/WPI/TCP_Server_CLI.SAPI.php
$TCP_Server_CLI->start();
