<?php

namespace Bootgly\ADI\Database;


use Bootgly\ACI\Tests\Suite;


return new Suite(
   // * Config
   autoBoot: __DIR__,
   autoInstance: true,
   autoReport: true,
   autoSummarize: true,
   exitOnFailure: true,
   // * Data
   suiteName: __NAMESPACE__,
   tests: [
      '1.1-construct-default_config',
      '2.1-query-operation',
      '2.2-operation-timeout',
      '2.3-result_views',
      '3.1-sql_drivers-postgresql_repository',
      '3.2-postgresql_encoder',
      '3.3-postgresql_decoder',
      '3.4-postgresql_operation_stream',
      '3.5-connection-non_blocking_connect',
      '4.1-pool-reuses_connection',
      '4.2-pool-max_colocation',
      '4.3-pool-created_bookkeeping',
      '4.4-pool-pending_forget',
      '5.1-postgresql_authentication_md5',
      '5.2-postgresql_authentication_scram',
      '5.3-postgresql_scram_state_machine',
      '6.1-postgresql_tls_prefer',
      '6.2-postgresql_tls_require',
      '6.3-postgresql_tls_accept',
      '7.1-postgresql_extended_encoder',
      '7.2-postgresql_extended_operation',
      '7.3-postgresql_prepared_cache',
      '7.4-postgresql_prepared_cache_lru',
      '7.5-postgresql_error_cleanup',
      '7.6-postgresql_result_types',
      '7.7-postgresql_parameter_oids',
      '7.8-postgresql_error_paths',
      '7.9-postgresql_cancel_request',
      '7.10-postgresql_result_advanced_types',
      '7.11-postgresql_statement_describe',
      '7.12-postgresql_pipeline',
      '7.13-postgresql_pipeline_release',
      '7.14-sql_transactions',
      '7.15-postgresql_transport_failures',
      '8.1-databases-registry',
      '8.2-paradigm-abstract',
      '8.3-kv_driver_fake',
      '8.5-kv_redis_async',
      '9.1-sqlite_driver_registry',
      '9.2-sqlite_connection_attach',
      '9.3-sqlite_query_simple',
      '9.4-sqlite_parameters_types',
      '9.5-sqlite_result_hydration',
      '9.6-sqlite_statement_cache',
      '9.7-sqlite_transactions',
      '9.8-sqlite_pool_file_concurrency',
      '9.9-sqlite_error_paths',
      '10.1-mysql_encoder',
      '10.2-mysql_decoder',
      '10.3-mysql_authentication',
      '10.4-mysql_handshake_native',
      '10.5-mysql_handshake_caching_sha2',
      '10.6-mysql_auth_switch',
      '10.7-mysql_tls_request',
      '10.8-mysql_query_text',
      '10.9-mysql_prepared_binary',
      '10.10-mysql_statement_cache',
      '10.11-mysql_ok_err_semantics',
      '10.12-mysql_serialization',
      '10.13-mysql_cancel_kill',
      '10.14-mysql_transactions',
      '10.15-mysql_e2e_live',
      '10.16-mysql_transport_failures',
      '10.17-mysql_event_head_flush',
      // ! Appended last so earlier case indexes stay stable.
      '8.6-sql_fallback_retry_state',
      '10.18-mysql_prepare_flag',
      '4.5-pool-finished_assign',
      '7.16-postgresql_float_text',
      '7.17-postgresql_encoder_value_formats',
      '7.18-postgresql_parameter_inference',
      '7.19-postgresql_statement_identity',
      '7.20-postgresql_error_lifecycle',
      '7.21-postgresql_transient_statements',
      '7.22-postgresql_close_holders',
      '10.19-mysql_abandoned_head',
      '4.6-pool-expiry_release',
      '10.20-mysql_abandon_contract',
      '7.23-postgresql_abandoned_pipeline',
      '4.7-pool-cancel_reconcile',
      '4.8-pool-release_unlock_precedence',
      '4.9-pool-pinned_dead_assign',
      '7.24-sql_transaction_serial_guard',
      '10.21-mysql_transaction_teardown',
      '7.25-postgresql_transaction_teardown',
      '9.10-sqlite_failed_statement_reuse',
      '9.11-sqlite_bind_mismatch',
      '10.22-mysql_prepare_window',
      '7.26-postgresql_prepare_window',
      '10.23-mysql_statement_pins',
      '10.24-mysql_insert_id_width',
      '4.10-pool-pending_wait',
      '8.7-kv_redis_transport_failures',
      '8.8-kv_redis_abandon_contract',
      '4.11-pool-finished_pipeline_gate',
      '7.27-sql_savepoint_stack',
      '7.28-postgresql_commit_tag',
      '7.29-postgresql_parse_order',
      '8.9-kv_redis_teardown_isolation',
      '4.12-pool-settled_claim',
      '4.13-pool-bookkeeping_invariant',
      '4.14-pool-cancel_preconditions',
      '7.30-sql_transaction_failed_begin',
      '9.12-sqlite_pool_confinement',
      '7.31-postgresql_stale_write_holder',
      '7.32-postgresql_stale_holder_live',
      '7.33-postgresql_teardown_holder',
   ]
);
